version : "3.5"

services :
  db:
    image : postgres
    restart: always
    environment:
      POSTGRES_DB: deltai
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - 5432
  web :
    build : .
    command: bash -c "python -m nltk.downloader stopwords && python /deltai/manage.py db upgrade && python /deltai/app.py"

    volumes: 
      - .:/deltai
    ports: 
      - 3002:3002
    depends_on:
      - db
    restart: always
    


