"""empty message

Revision ID: b3229b399162
Revises: 
Create Date: 2020-04-08 17:06:30.345238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3229b399162'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    newspaper_table = op.create_table('newspaper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('newspaper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['newspaper_id'], ['newspaper.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('news_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


    op.bulk_insert(newspaper_table,
        [
            {'id':1, 'name':'El Universal', 'url': 'https://eluniversal.com.mx'},
            {'id':2, 'name':'La Prensa', 'url': 'https://www.la-prensa.com.mx'},
            {'id':3, 'name':'La Jornada', 'url' : 'https://www.jornada.com.mx' },
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_tag')
    op.drop_table('news')
    op.drop_table('tag')
    op.drop_table('newspaper')
    # ### end Alembic commands ###
